from pygame import Rect

BUTTON_WIDTH = 300
BUTTON_HEIGHT = 50

BUTTON_AREA_WIDTH = int(BUTTON_WIDTH * 1.05)
BUTTON_AREA_HEIGHT = int(BUTTON_HEIGHT * 1.05)

BUTTON_RECT = Rect(0, 0, BUTTON_WIDTH, BUTTON_HEIGHT)
BUTTON_AREA_RECT = Rect(0, 0, BUTTON_AREA_WIDTH, BUTTON_AREA_HEIGHT)